# Use root/example as user/password credentials
version: '3.1'

services:
  go:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    command:
      - "mysqld"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
      - "--init-file=/docker-entrypoint-initdb.d/init.sql"
    restart: always
    environment:
      MYSQL_DATABASE: dockermysql
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./tmp/db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8001:3306"
